version: '2'
services:
  es_tsm_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: estsm
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - tsesdata1:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
      - 9303:9300
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    environment:
      SERVER_NAME: kibana.fundrequest.io
      ELASTICSEARCH_URL: http://estsm:9200
    networks:
      - esnet
    ports:
      - 5603:5601

  tsm_rabbitmq:
    image: rabbitmq:3.6.8-management
    ports :
      -  "5673:5672"
      -  "9193:15672"
    volumes:
      - ./docker_data/monitor/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=default_pass
    networks:
      - esnet

volumes:
  tsesdata1:
    driver: local

networks:
  esnet: